# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QLGV_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pyodbc
from PyQt5 import QtCore, QtGui, QtWidgets
from DBHelper import *
from PyQt5.QtWidgets import *


class Ui_Dialog0(object):
    def setup(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 612)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 70, 321, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.mGVLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.mGVLabel.setObjectName("mGVLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mGVLabel)
        self.HTLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.HTLabel.setObjectName("HTLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.HTLabel)
        self.HTLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.HTLineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.HTLineEdit.setObjectName("HTLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HTLineEdit)
        self.hCVLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.hCVLabel.setObjectName("hCVLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.hCVLabel)
        self.hCVComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.hCVComboBox.setObjectName("hCVComboBox")
        self.hCVComboBox.addItem("")
        self.hCVComboBox.addItem("")
        self.hCVComboBox.addItem("")
        self.hCVComboBox.addItem("")
        self.hCVComboBox.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.hCVComboBox)
        self.hCHMLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.hCHMLabel.setObjectName("hCHMLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.hCHMLabel)
        self.hCHMComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.hCHMComboBox.setObjectName("hCHMComboBox")
        self.hCHMComboBox.addItem("")
        self.hCHMComboBox.addItem("")
        self.hCHMComboBox.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.hCHMComboBox)
        self.namLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.namLabel.setObjectName("namLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.namLabel)
        self.namCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.namCheckBox.setObjectName("namCheckBox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.namCheckBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_3)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 301, 1200, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(250, 260, 681, 30))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(410, 70, 341, 161))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.ngYSinhLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.ngYSinhLabel_2.setObjectName("ngYSinhLabel_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ngYSinhLabel_2)
        self.ngYSinhDateEdit_2 = QtWidgets.QDateEdit(self.formLayoutWidget_2)
        self.ngYSinhDateEdit_2.setObjectName("ngYSinhDateEdit_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ngYSinhDateEdit_2)
        self.aChLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.aChLabel_2.setObjectName("aChLabel_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.aChLabel_2)
        self.aChLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.aChLineEdit_2.setObjectName("aChLineEdit_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.aChLineEdit_2)
        self.chuyNMNLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.chuyNMNLabel_2.setObjectName("chuyNMNLabel_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.chuyNMNLabel_2)
        self.chuyNMNLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.chuyNMNLineEdit_2.setObjectName("chuyNMNLineEdit_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.chuyNMNLineEdit_2)
        self.angLMViCLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.angLMViCLabel_2.setObjectName("angLMViCLabel_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.angLMViCLabel_2)
        self.angLMViCCheckBox_2 = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.angLMViCCheckBox_2.setObjectName("angLMViCCheckBox_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.angLMViCCheckBox_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_3.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_6)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(500, 30, 351, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(780, 60, 181, 150))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setGeometry(QtCore.QRect(980, 60, 181, 150))
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(1030, 220, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 220, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(790, 30, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(990, 30, 111, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Tải dữ liệu cho Table, cho chọn dòng, bắt trỏ chuột.
        self.loaddataTable()
        self.tableWidget.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.tableWidget.clicked.connect(self.tableClick)

        # Combobox HV, HH
        self.hCVComboBox.setEditable(True)
        self.hCHMComboBox.setEditable(True)

        self.label.setText(self.taoMaGV())
        # Nút chức năng
        self.pushButton_8.clicked.connect(self.nutLamMoi)
        self.pushButton_9.clicked.connect(self.nutThem)
        self.pushButton_10.clicked.connect(self.nutXoa)
        self.pushButton_11.clicked.connect(self.nutSua)
        self.pushButton_10.setEnabled(False)
        self.pushButton_11.setEnabled(False)

        # -----------------------Môn Học----------------------------
        # MH chưa chọn
        self.loaddataListMH()
        # self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)

        # MH chọn

        # Nút
        self.pushButton_2.clicked.connect(self.nutGoMH)
        self.pushButton.clicked.connect(self.nutBackMH)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "QLDSV"))
        self.mGVLabel.setText(_translate("Dialog", "Mã GV:"))
        self.HTLabel.setText(_translate("Dialog", "Họ Tên:"))
        self.hCVLabel.setText(_translate("Dialog", "Học Vị:"))
        self.hCVComboBox.setItemText(0, _translate("Dialog", "Không"))
        self.hCVComboBox.setItemText(1, _translate("Dialog", "Cử nhân"))
        self.hCVComboBox.setItemText(2, _translate("Dialog", "Thạc Sĩ"))
        self.hCVComboBox.setItemText(3, _translate("Dialog", "Tiến Sĩ"))
        self.hCVComboBox.setItemText(4, _translate("Dialog", "Tiến Sĩ Khoa Học"))

        self.hCHMLabel.setText(_translate("Dialog", "Học Hàm"))
        self.hCHMComboBox.setItemText(0, _translate("Dialog", "Không"))
        self.hCHMComboBox.setItemText(1, _translate("Dialog", "Phó giáo sư"))
        self.hCHMComboBox.setItemText(2, _translate("Dialog", "Giáo sư"))

        self.namLabel.setText(_translate("Dialog", "Nam:"))
        self.label.setText(_translate("Dialog", "GV1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Mã GV"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Họ Tên"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Học Vị"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Học Hàm"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Phái"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Ngày Sinh"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Địa Chỉ"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Chuyên Môn"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Trạng Thái"))
        self.pushButton_8.setText(_translate("Dialog", "Làm mới"))
        self.pushButton_9.setText(_translate("Dialog", "Thêm"))
        self.pushButton_10.setText(_translate("Dialog", "Xóa"))
        self.pushButton_11.setText(_translate("Dialog", "Sửa"))
        self.ngYSinhLabel_2.setText(_translate("Dialog", "Ngày Sinh:"))
        self.aChLabel_2.setText(_translate("Dialog", "Địa Chỉ:"))
        self.chuyNMNLabel_2.setText(_translate("Dialog", "Chuyên Môn:"))
        self.angLMViCLabel_2.setText(_translate("Dialog", "Đang Làm Việc:"))
        self.label_4.setText(_translate("Dialog", "QUẢN LÝ GIẢNG VIÊN"))
        self.pushButton.setText(_translate("Dialog", "<<"))
        self.pushButton_2.setText(_translate("Dialog", ">>"))
        self.label_2.setText(_translate("Dialog", "Các môn hiện có:"))
        self.label_3.setText(_translate("Dialog", "Các môn GV dạy:"))

    # Hàm tải dữ liệu lên cho table
    def loaddataTable(self):
        sqlquery = "select * from giangvien order by cast(substring(MaGV,3,10) as int)"
        self.tableWidget.setRowCount(50)
        tablerow = 0
        # đặt số cột, và dữ liệu ở mỗi cột
        for row in ketnoi().execute(sqlquery):
            self.tableWidget.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
            self.tableWidget.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(row[1]))
            self.tableWidget.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(row[2]))
            self.tableWidget.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(row[3]))
            self.tableWidget.setItem(tablerow, 4,
                                     QtWidgets.QTableWidgetItem("Nam" if str(row[4]).__eq__("True") else "Nữ"))
            self.tableWidget.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(row[5]))
            self.tableWidget.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(row[6]))
            self.tableWidget.setItem(tablerow, 7, QtWidgets.QTableWidgetItem(row[7]))
            self.tableWidget.setItem(tablerow, 8, QtWidgets.QTableWidgetItem(
                "Đã nghỉ" if str(row[8]).__eq__("True") else "Đang làm việc"))

            tablerow += 1
        self.tableWidget.setRowCount(tablerow)
        # Khong cho edit
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)

        # Sửa kích cỡ cột
        self.tableWidget.setColumnWidth(1, 150)

    # Hàm bắt event table click tải dữ liệu lên ô để sửa
    def tableClick(self):
        self.pushButton_9.setEnabled(False)
        self.pushButton_10.setEnabled(True)
        self.pushButton_11.setEnabled(True)
        row = self.tableWidget.currentRow()
        self.label.setText(self.tableWidget.item(row, 0).text())
        self.HTLineEdit.setText(self.tableWidget.item(row, 1).text())
        self.hCVComboBox.setCurrentText(self.tableWidget.item(row, 2).text())
        self.hCHMComboBox.setCurrentText(self.tableWidget.item(row, 3).text())
        if self.tableWidget.item(row, 4).text() == "Nam":
            self.namCheckBox.setChecked(True)
        else:
            self.namCheckBox.setChecked(False)
        self.ngYSinhDateEdit_2.setDate(QtCore.QDate(int((str(self.tableWidget.item(row, 5).text())[0:4])),
                                                    int((str(self.tableWidget.item(row, 5).text())[5:7])),
                                                    int((str(self.tableWidget.item(row, 5).text())[8:10]))))
        self.aChLineEdit_2.setText(self.tableWidget.item(row, 6).text())
        self.chuyNMNLineEdit_2.setText(self.tableWidget.item(row, 7).text())

        if self.tableWidget.item(row, 8).text() == "Đang làm việc":
            self.angLMViCCheckBox_2.setChecked(True)
        else:
            self.angLMViCCheckBox_2.setChecked(False)

        self.loaddataListMH()
        self.loaddataListMHChon()

    def taoMaGV(self):
        sqlquery = "select maGV from giangvien"
        max = 0
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(", "", 2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
            ma = int((str(e)[2:4]))
            if ma > max:
                max = ma
        return "GV" + str(max + 1)

    # Nút Làm Mới
    def nutLamMoi(self):
        self.loaddataTable()
        self.tableWidget.clearSelection()
        self.label.setText(self.taoMaGV())
        self.HTLineEdit.setText("")
        self.hCVComboBox.setCurrentIndex(0)
        self.hCHMComboBox.setCurrentIndex(0)
        self.namCheckBox.setChecked(False)
        self.ngYSinhDateEdit_2.setDate(QtCore.QDate.currentDate())
        self.aChLineEdit_2.setText("")
        self.chuyNMNLineEdit_2.setText("")
        self.angLMViCCheckBox_2.setChecked(False)
        self.pushButton_11.setEnabled(False)
        self.pushButton_9.setEnabled(True)
        self.pushButton_10.setEnabled(False)
        self.pushButton_11.setEnabled(False)
        self.loaddataListMH()
        self.loaddataListMHChon()

    # Nút Thêm
    def nutThem(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()

        a = self.label.text()
        b = self.HTLineEdit.text()
        c = self.hCVComboBox.currentText()
        d = self.hCHMComboBox.currentText()
        e = "0"
        if self.namCheckBox.isChecked():
            c = "1"
        f = str(str(self.ngYSinhDateEdit_2.date().year()) + "-" + str(self.ngYSinhDateEdit_2.date().month()) + "-" + \
                str(self.ngYSinhDateEdit_2.date().day()))
        g = self.aChLineEdit_2.text()
        h = self.chuyNMNLineEdit_2.text()
        i = "1"
        if self.angLMViCCheckBox_2.isChecked():
            i = "0"

        query = "insert into giangvien values('" + a + "',N'" + b + "','" + c + "','" + d + "','" + e + "','" + f + "','" + g + "','" + h + "','" + i + "')"
        print(query)
        try:
            cur.execute(query)
            conn.commit()
            self.label.setText(self.taoMaGV())
            DBHelper.textThongBao = "         Thêm thành công."
            hienTB(self)
            print("Ok")
        except:
            print("Fail")
        self.nutLamMoi()

    # Nút Xóa
    def nutXoa(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()
        a = self.label.text()
        print(a)
        query = "delete from giangvien where magv='" + a + "'"
        try:
            self.deleteDay()
            cur.execute(query)
            conn.commit()
            DBHelper.textThongBao = "         Xóa thành công."
            hienTB(self)
            print("Ok")
        except:
            print("Fail")
        self.nutLamMoi()

    # Nút Sửa
    def nutSua(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()

        a = self.label.text()
        b = self.HTLineEdit.text()
        c = self.hCVComboBox.currentText()
        d = self.hCHMComboBox.currentText()
        e = "0"
        if self.namCheckBox.isChecked():
            c = "1"
        f = str(str(self.ngYSinhDateEdit_2.date().year()) + "-" + str(self.ngYSinhDateEdit_2.date().month()) + "-" + \
                str(self.ngYSinhDateEdit_2.date().day()))
        g = self.aChLineEdit_2.text()
        h = self.chuyNMNLineEdit_2.text()
        i = "1"
        if self.angLMViCCheckBox_2.isChecked():
            i = "0"

        query = "update giangvien set [HoTen]=N'" + b + "',[HocVi]=N'" + c + "',[HocHam]=N'" + d + "',[Phai]=N'" + e + "',[NgaySinh]='" + f + "',[DiaChi]=N'" + g + "',[ChuyenMon]=N'" + h + "',[TrangThaiNghi]='" + i + "' where magv = '" + a + "'"
        print(query)
        try:
            self.deleteDay()
            self.insertDay()
            cur.execute(query)
            conn.commit()
            DBHelper.textThongBao = "         Sửa thành công."
            hienTB(self)
            print("Ok")
        except:
            print("Fail")
        self.nutLamMoi()


    # ------------------------Môn Học------------------------

    # Hàm chuyển tên Môn sang mã Môn
    def searchMaMH(self, a):
        sqlquery = "SELECT MaMH FROM MonHoc WHERE TenMH=N'" + a + "'"
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(", "", 2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
        return e

    def loaddataListMH(self):
        self.listWidget.clear()
        a = self.label.text()
        sqlquery="{call DS_MH_CHUACHON_GV('"+a+"')}"
        tablerow=0
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(", "", 2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
            self.listWidget.addItem(QtWidgets.QListWidgetItem(e))
            tablerow+=1

    def loaddataListMHChon(self):
        self.listWidget_2.clear()
        a = self.label.text()
        sqlquery="{call DS_MHCHON_GV('"+a+"')}"
        tablerow=0
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(", "", 2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
            self.listWidget_2.addItem(QtWidgets.QListWidgetItem(e))
            tablerow+=1

    # Nút Go Môn Học
    def nutGoMH(self):
        # print("Go")
        # print(self.listWidget.currentRow())
        if self.listWidget.currentRow() != -1 and self.listWidget.item(self.listWidget.currentRow()).isHidden()==False:
            self.listWidget_2.addItem(self.listWidget.currentItem().text())
            self.listWidget.currentItem().setHidden(True)

    # Nút Back Môn Học
    def nutBackMH(self):
        # print("Back")
        # print(self.listWidget_2.currentRow())
        if self.listWidget_2.currentRow() != -1 and self.listWidget_2.item(self.listWidget_2.currentRow()).isHidden()==False:
            self.listWidget.addItem(self.listWidget_2.currentItem().text())
            self.listWidget_2.currentItem().setHidden(True)

    def insertDay(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()
        a=self.label.text()
        for row in range(self.listWidget_2.count()):
            if self.listWidget_2.item(row).isHidden()==False:
                b=self.searchMaMH(self.listWidget_2.item(row).text())
                sqlquery = "insert into day values('" + a + "','" + b + "')"
                print(sqlquery)
                try:
                    cur.execute(sqlquery)
                    conn.commit()
                    print("Ok")
                except:
                    print("Fail")

    def deleteDay(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()
        a=self.label.text()
        sqlquery = "delete from day where magv='" + a + "'"
        print(sqlquery)
        try:
            cur.execute(sqlquery)
            conn.commit()
            print("Ok")
        except:
            print("Fail")

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog0()
    ui.setup(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
