# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QLMH_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pyodbc
from PyQt5 import QtCore, QtGui, QtWidgets
from DBHelper import *

class Ui_Dialog5(object):
    def setup(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1124, 639)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(30, 301, 1051, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(600, 80, 341, 166))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.ngYSinhLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.ngYSinhLabel_2.setObjectName("ngYSinhLabel_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ngYSinhLabel_2)
        self.ngYSinhLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.ngYSinhLabel_3.setObjectName("ngYSinhLabel_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ngYSinhLabel_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_3.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_6)
        self.dYCCMNLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.dYCCMNLabel_2.setObjectName("dYCCMNLabel_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.dYCCMNLabel_2)
        self.HTLineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.HTLineEdit_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.HTLineEdit_3.setObjectName("HTLineEdit_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.HTLineEdit_3)
        self.HTLineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.HTLineEdit_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.HTLineEdit_4.setObjectName("HTLineEdit_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HTLineEdit_4)
        self.HTLineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.HTLineEdit_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.HTLineEdit_5.setObjectName("HTLineEdit_5")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.HTLineEdit_5)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(500, 30, 351, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(260, 80, 321, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.mGVLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.mGVLabel.setObjectName("mGVLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mGVLabel)
        self.HTLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.HTLabel.setObjectName("HTLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.HTLabel)
        self.HTLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.HTLineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.HTLineEdit.setObjectName("HTLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HTLineEdit)
        self.hCVLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.hCVLabel.setObjectName("hCVLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.hCVLabel)
        self.hCHMLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.hCHMLabel.setObjectName("hCHMLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.hCHMLabel)
        self.namLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.namLabel.setObjectName("namLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.namLabel)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_3)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.aChLineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.aChLineEdit_4.setObjectName("aChLineEdit_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.aChLineEdit_4)
        self.aChLineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.aChLineEdit_5.setObjectName("aChLineEdit_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.aChLineEdit_5)
        self.HTLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.HTLineEdit_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.HTLineEdit_2.setObjectName("HTLineEdit_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.HTLineEdit_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(250, 260, 681, 30))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Tải dữ liệu cho Table, cho chọn dòng, bắt trỏ chuột.
        self.loaddataTable()
        self.tableWidget.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.tableWidget.clicked.connect(self.tableClick)

        self.label.setText(self.taoMaMH())
        #Nút chức năng
        self.pushButton_8.clicked.connect(self.nutLamMoi)
        self.pushButton_9.clicked.connect(self.nutThem)
        self.pushButton_10.clicked.connect(self.nutXoa)
        self.pushButton_11.clicked.connect(self.nutSua)
        self.pushButton_10.setEnabled(False)
        self.pushButton_11.setEnabled(False)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "QLDSV"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Mã MH"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Tên MH"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Số tiết LT"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Số tiết TH"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Số tín chỉ"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "HS chuyên cần"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "HS giữa kì"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "HS cuối kì"))
        self.ngYSinhLabel_2.setText(_translate("Dialog", "Hệ số chuyên cần(%):"))
        self.ngYSinhLabel_3.setText(_translate("Dialog", "Hệ số giữa kì(%):"))
        self.dYCCMNLabel_2.setText(_translate("Dialog", "Hệ số cuối kì(%):"))
        self.label_4.setText(_translate("Dialog", "QUẢN LÝ MÔN HỌC"))
        self.mGVLabel.setText(_translate("Dialog", "Mã MH:"))
        self.HTLabel.setText(_translate("Dialog", "Tên MH:"))
        self.hCVLabel.setText(_translate("Dialog", "Số tiết lý thuyết:"))
        self.hCHMLabel.setText(_translate("Dialog", "Số tiết thực hành:"))
        self.namLabel.setText(_translate("Dialog", "Số tín chỉ:"))
        self.label.setText(_translate("Dialog", "MH1"))
        self.pushButton_8.setText(_translate("Dialog", "Làm mới"))
        self.pushButton_9.setText(_translate("Dialog", "Thêm"))
        self.pushButton_10.setText(_translate("Dialog", "Xóa"))
        self.pushButton_11.setText(_translate("Dialog", "Sửa"))

    # Hàm tải dữ liệu lên cho table
    def loaddataTable(self):
        sqlquery = "select * from monhoc order by cast(substring(MaMH,3,10) as int)"
        self.tableWidget.setRowCount(50)
        tablerow = 0
        # đặt số cột, và dữ liệu ở mỗi cột
        for row in ketnoi().execute(sqlquery):
            self.tableWidget.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
            self.tableWidget.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(row[1]))
            self.tableWidget.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(str(row[2])))
            self.tableWidget.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(str(row[3])))
            self.tableWidget.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(str(row[4])))
            self.tableWidget.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(str(row[5])))
            self.tableWidget.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(str(row[6])))
            self.tableWidget.setItem(tablerow, 7, QtWidgets.QTableWidgetItem(str(row[7])))
            tablerow += 1
        self.tableWidget.setRowCount(tablerow)

        # Khong cho edit
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)

    # Hàm bắt event table click tải dữ liệu lên ô để sửa
    def tableClick(self):
        self.pushButton_9.setEnabled(False)
        self.pushButton_10.setEnabled(True)
        self.pushButton_11.setEnabled(True)
        row = self.tableWidget.currentRow()
        self.label.setText(self.tableWidget.item(row, 0).text())
        self.HTLineEdit.setText(self.tableWidget.item(row, 1).text())
        self.HTLineEdit_2.setText(self.tableWidget.item(row, 2).text())
        self.aChLineEdit_4.setText(self.tableWidget.item(row, 3).text())
        self.aChLineEdit_5.setText(self.tableWidget.item(row, 4).text())
        self.HTLineEdit_3.setText(self.tableWidget.item(row, 5).text())
        self.HTLineEdit_4.setText(self.tableWidget.item(row, 6).text())
        self.HTLineEdit_5.setText(self.tableWidget.item(row, 7).text())

    def taoMaMH(self):
        sqlquery = "select maMH from monhoc"
        max=0
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(", "", 2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
            ma = int((str(e)[2:4]))
            if ma>max:
                max=ma
        return "MH"+str(max+1)

    # Nút Làm Mới
    def nutLamMoi(self):
        self.loaddataTable()
        self.tableWidget.clearSelection()
        self.label.setText(self.taoMaMH())
        self.HTLineEdit.setText("")
        self.HTLineEdit_2.setText("")
        self.aChLineEdit_4.setText("")
        self.aChLineEdit_5.setText("")
        self.HTLineEdit_3.setText("")
        self.HTLineEdit_4.setText("")
        self.HTLineEdit_5.setText("")
        self.pushButton_9.setEnabled(True)
        self.pushButton_10.setEnabled(False)
        self.pushButton_11.setEnabled(False)

    # Nút Thêm
    def nutThem(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()

        a=self.label.text()
        b=self.HTLineEdit.text()
        c=self.HTLineEdit_2.text()
        d=self.aChLineEdit_4.text()
        e=self.aChLineEdit_5.text()
        f=self.HTLineEdit_3.text()
        g=self.HTLineEdit_4.text()
        h=self.HTLineEdit_5.text()

        query="insert into monhoc values('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"','"+f+"','"+g+"','"+h+"')"
        print(query)
        try:
            cur.execute(query)
            conn.commit()
            self.label.setText(self.taoMaMH())
            DBHelper.textThongBao = "         Thêm thành công."
            hienTB(self)
            print("Ok")
        except:
            print("Fail")
        self.nutLamMoi()

    # Nút Xóa
    def nutXoa(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()
        a = self.label.text()
        print(a)
        query = "delete from monhoc where mamh='" + a + "'"
        try:
            cur.execute(query)
            conn.commit()
            DBHelper.textThongBao = "         Xóa thành công."
            hienTB(self)
            print("Ok")
        except:
            print("Fail")
        self.nutLamMoi()

    # Nút Sửa
    def nutSua(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()

        a = self.label.text()
        b = self.HTLineEdit.text()
        c = self.HTLineEdit_2.text()
        d = self.aChLineEdit_4.text()
        e = self.aChLineEdit_5.text()
        f = self.HTLineEdit_3.text()
        g = self.HTLineEdit_4.text()
        h = self.HTLineEdit_5.text()

        query = "update monhoc set [TenMH]=N'" + b + "',[SoTietLT]='" + c + "',[SoTietTH]='" + d + "',[SoTinChi]='" + e + "',[HeSoCC]='" + f + "',[HeSoGK]='" + g + "',[HeSoCK]='" + h + "' where mamh = '"+a+"'"
        print(query)
        try:
            cur.execute(query)
            conn.commit()
            print("Ok")
            DBHelper.textThongBao = "         Sửa thành công."
            hienTB(self)
        except:
            print("Fail")
        self.nutLamMoi()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog5()
    ui.setup(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
