# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QLNL_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import DBHelper
import Treeeeeee
from DBHelper import *
import pyodbc
from Treeeeeee import *


class Ui_DialogXemNL(object):
    def setup(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(747, 390)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 100, 321, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.mGVLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.mGVLabel.setObjectName("mGVLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mGVLabel)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.HTLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.HTLabel.setObjectName("HTLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.HTLabel)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_3)
        self.HTLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.HTLabel_2.setObjectName("HTLabel_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.HTLabel_2)
        self.dYCCMNComboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.dYCCMNComboBox_2.setObjectName("dYCCMNComboBox_2")
        self.dYCCMNComboBox_2.addItem("")
        self.dYCCMNComboBox_2.addItem("")
        self.dYCCMNComboBox_2.addItem("")
        self.dYCCMNComboBox_2.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dYCCMNComboBox_2)
        self.hCHMLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.hCHMLabel_2.setObjectName("hCHMLabel_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.hCHMLabel_2)
        self.dYCCMNComboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.dYCCMNComboBox_3.setObjectName("dYCCMNComboBox_3")
        self.dYCCMNComboBox_3.addItem("")
        self.dYCCMNComboBox_3.addItem("")
        self.dYCCMNComboBox_3.addItem("")
        self.dYCCMNComboBox_3.addItem("")
        self.dYCCMNComboBox_3.addItem("")
        self.dYCCMNComboBox_3.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dYCCMNComboBox_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(280, 50, 351, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 300, 681, 30))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_3.addWidget(self.pushButton_12)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.dYCCMNComboBox_6 = QtWidgets.QComboBox(Dialog)
        self.dYCCMNComboBox_6.setGeometry(QtCore.QRect(521, 175, 178, 22))
        self.dYCCMNComboBox_6.setObjectName("dYCCMNComboBox_6")
        self.dYCCMNComboBox_6.addItem("")
        self.dYCCMNComboBox_6.addItem("")
        self.dYCCMNComboBox_6.addItem("")
        self.dYCCMNComboBox_6.addItem("")
        self.dYCCMNComboBox_4 = QtWidgets.QComboBox(Dialog)
        self.dYCCMNComboBox_4.setGeometry(QtCore.QRect(521, 117, 178, 22))
        self.dYCCMNComboBox_4.setObjectName("dYCCMNComboBox_4")
        self.dYCCMNComboBox_4.addItem("")
        self.dYCCMNComboBox_4.addItem("")
        self.dYCCMNComboBox_4.addItem("")
        self.dYCCMNComboBox_4.addItem("")
        self.dYCCMNComboBox_5 = QtWidgets.QComboBox(Dialog)
        self.dYCCMNComboBox_5.setGeometry(QtCore.QRect(521, 146, 178, 22))
        self.dYCCMNComboBox_5.setObjectName("dYCCMNComboBox_5")
        self.dYCCMNComboBox_5.addItem("")
        self.dYCCMNComboBox_5.addItem("")
        self.dYCCMNComboBox_5.addItem("")
        self.dYCCMNComboBox_5.addItem("")
        self.namLabel_2 = QtWidgets.QLabel(Dialog)
        self.namLabel_2.setGeometry(QtCore.QRect(380, 117, 134, 22))
        self.namLabel_2.setObjectName("namLabel_2")
        self.namLabel_3 = QtWidgets.QLabel(Dialog)
        self.namLabel_3.setGeometry(QtCore.QRect(380, 146, 100, 22))
        self.namLabel_3.setObjectName("namLabel_3")
        self.namLabel_4 = QtWidgets.QLabel(Dialog)
        self.namLabel_4.setGeometry(QtCore.QRect(380, 175, 47, 22))
        self.namLabel_4.setObjectName("namLabel_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.label.setText(self.taoMaNL())
        self.tracuuMaNL()
        self.label_2.setText(DBHelper.masv_formnl)

        #
        #
        #
        # Nút
        self.pushButton_9.clicked.connect(self.nutThem)
        self.pushButton_10.clicked.connect(self.nutXoa)
        self.pushButton_11.clicked.connect(self.nutSua)
        self.pushButton_12.clicked.connect(self.nutThoat)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.mGVLabel.setText(_translate("Dialog", "Mã năng lực:"))
        self.label.setText(_translate("Dialog", "NL1"))
        self.HTLabel.setText(_translate("Dialog", "Mã SV:"))
        self.label_2.setText(_translate("Dialog", "..."))
        self.HTLabel_2.setText(_translate("Dialog", "Nhận xét thực tập:"))
        self.dYCCMNComboBox_2.setItemText(0, _translate("Dialog", "Kem"))
        self.dYCCMNComboBox_2.setItemText(1, _translate("Dialog", "Trung Binh"))
        self.dYCCMNComboBox_2.setItemText(2, _translate("Dialog", "Kha"))
        self.dYCCMNComboBox_2.setItemText(3, _translate("Dialog", "Tot"))
        self.hCHMLabel_2.setText(_translate("Dialog", "Trình độ ngoại ngữ:"))
        self.dYCCMNComboBox_3.setItemText(0, _translate("Dialog", "Beginner"))
        self.dYCCMNComboBox_3.setItemText(1, _translate("Dialog", "Elementary"))
        self.dYCCMNComboBox_3.setItemText(2, _translate("Dialog", "Pre-Intermediate"))
        self.dYCCMNComboBox_3.setItemText(3, _translate("Dialog", "Intermediate"))
        self.dYCCMNComboBox_3.setItemText(4, _translate("Dialog", "Upper-Intermediate"))
        self.dYCCMNComboBox_3.setItemText(5, _translate("Dialog", "Advanced"))
        self.label_4.setText(_translate("Dialog", "QUẢN LÝ NĂNG LỰC"))
        self.pushButton_9.setText(_translate("Dialog", "Thêm"))
        self.pushButton_10.setText(_translate("Dialog", "Xóa"))
        self.pushButton_11.setText(_translate("Dialog", "Sửa"))
        self.pushButton_12.setText(_translate("Dialog", "Thoát"))
        self.dYCCMNComboBox_6.setItemText(0, _translate("Dialog", "Kem"))
        self.dYCCMNComboBox_6.setItemText(1, _translate("Dialog", "Trung Binh"))
        self.dYCCMNComboBox_6.setItemText(2, _translate("Dialog", "Kha"))
        self.dYCCMNComboBox_6.setItemText(3, _translate("Dialog", "Tot"))
        self.dYCCMNComboBox_4.setItemText(0, _translate("Dialog", "Kem"))
        self.dYCCMNComboBox_4.setItemText(1, _translate("Dialog", "Trung Binh"))
        self.dYCCMNComboBox_4.setItemText(2, _translate("Dialog", "Kha"))
        self.dYCCMNComboBox_4.setItemText(3, _translate("Dialog", "Tot"))
        self.dYCCMNComboBox_5.setItemText(0, _translate("Dialog", "Kem"))
        self.dYCCMNComboBox_5.setItemText(1, _translate("Dialog", "Trung Binh"))
        self.dYCCMNComboBox_5.setItemText(2, _translate("Dialog", "Kha"))
        self.dYCCMNComboBox_5.setItemText(3, _translate("Dialog", "Tot"))
        self.namLabel_2.setText(_translate("Dialog", "Kĩ năng làm việc nhóm:"))
        self.namLabel_3.setText(_translate("Dialog", "Kĩ năng giao tiếp:"))
        self.namLabel_4.setText(_translate("Dialog", "Học lực:"))

    def taoMaNL(self):
        sqlquery = "select maNL from nangluc"
        max = 0
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(", "", 2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
            ma = int((str(e)[2:4]))
            if ma > max:
                max = ma
        return "NL" + str(max + 1)

    # Nút Thêm
    def nutThem(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()

        a = self.label.text()
        b = self.dYCCMNComboBox_2.currentText()
        c = self.dYCCMNComboBox_3.currentText()
        d = self.dYCCMNComboBox_4.currentText()
        e = self.dYCCMNComboBox_5.currentText()
        f = self.dYCCMNComboBox_6.currentText()
        g = self.label_2.text()

        query = "insert into nangluc values('" + a + "','" + b + "',N'" + c + "',N'" + d + "',N'" + e + "',N'" + f + "','" + g + "')"
        query1 = "update Sinhvien set [DanhGia]=N'"+ self.danhgiaAI()+ "' where masv= '" + self.label_2.text() + "'"
        print(query)
        try:
            cur.execute(query)
            cur.execute(query1)
            conn.commit()
            print("Ok")
            DBHelper.textThongBao = "         Thêm thành công."
            # danhgia= Treeeeeee.main(self.dYCCMNComboBox_2.currentIndex(),self.dYCCMNComboBox_3.currentIndex(),self.dYCCMNComboBox_4.currentIndex(),self.dYCCMNComboBox_5.currentIndex(),self.dYCCMNComboBox_6.currentIndex())
            # print()
            hienTB(self)
            self.pushButton_9.setEnabled(False)
            self.pushButton_10.setEnabled(True)
            self.pushButton_11.setEnabled(True)
        except:
            print("Fail")

    # Nút Xóa
    def nutXoa(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()
        a = self.label.text()
        b = self.dYCCMNComboBox_2.currentText()
        c = self.dYCCMNComboBox_3.currentText()
        d = self.dYCCMNComboBox_4.currentText()
        e = self.dYCCMNComboBox_5.currentText()
        f = self.dYCCMNComboBox_6.currentText()
        g = self.label_2.text()

        print(a)
        query = "delete from nangluc where manl='" + self.label.text() + "'"
        try:
            cur.execute(query)
            conn.commit()
            print("Ok")
            DBHelper.textThongBao = "         Xóa thành công."
            hienTB(self)
            self.pushButton_9.setEnabled(True)
            self.pushButton_10.setEnabled(False)
            self.pushButton_11.setEnabled(False)
        except:
            print("Fail")

    # Nút Sửa
    def nutSua(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()
        # print(self.danhgiaAI())
        # masv=self.
        a = self.label.text()
        b = self.dYCCMNComboBox_2.currentText()
        c = self.dYCCMNComboBox_3.currentText()
        d = self.dYCCMNComboBox_4.currentText()
        e = self.dYCCMNComboBox_5.currentText()
        f = self.dYCCMNComboBox_6.currentText()
        query = "update nangluc set [NhanxetTT]=N'" + b + "',[TrinhDoNN]=N'" + c + "',[KiNangLVN]=N'" + d + "',[KiNangGT]='" + e + "',[Hocluc]=N'" + f + "' where manl= '" + a + "'"
        query1 = "update Sinhvien set [DanhGia]=N'"+ self.danhgiaAI()+ "' where masv= '" + self.label_2.text() + "'"

        print(query)
        print(query1)
        try:
            cur.execute(query)
            cur.execute(query1)
            conn.commit()
            print("Ok")
            DBHelper.textThongBao = "         Sửa thành công."
            hienTB(self)
            self.pushButton_9.setEnabled(False)
            self.pushButton_10.setEnabled(True)
            self.pushButton_11.setEnabled(True)
        except:
            print("Fail")
        try:
            cur.execute(query1)
            conn.commit()
            print("Ok")
        except:
            print("Fail")

    # Nút thoát
    def nutThoat(self):
        print("Thoat")

    # hàm tra cứu mã năng lực
    def tracuuMaNL(self):
        self.pushButton_10.setEnabled(False)
        self.pushButton_11.setEnabled(False)
        query = "select * from nangluc where maSV='" + DBHelper.masv_formnl + "'"
        print(query)
        for row in ketnoi().execute(query):
            print(str(row[0]))
            if str(row[0]) != "":
                print("True")
                # a = self.label.text()
                # b = self.dYCCMNComboBox_2.currentText()
                # c = self.dYCCMNComboBox_3.currentText()
                # d = self.dYCCMNComboBox_4.currentText()
                # e = self.dYCCMNComboBox_5.currentText()
                # f = self.dYCCMNComboBox_6.currentText()
                self.label.setText(str(row[0]))
                self.dYCCMNComboBox_2.setCurrentText(str(row[1]))
                self.dYCCMNComboBox_3.setCurrentText(str(row[2]))
                self.dYCCMNComboBox_4.setCurrentText(str(row[3]))
                self.dYCCMNComboBox_5.setCurrentText(str(row[4]))
                self.dYCCMNComboBox_6.setCurrentText(str(row[5]))
                self.pushButton_9.setEnabled(False)
                self.pushButton_10.setEnabled(True)
                self.pushButton_11.setEnabled(True)

    # Hàm lấy đánh giá
    def danhgiaAI(self):
        danhgia = str(Treeeeeee.main(self.dYCCMNComboBox_2.currentIndex(), self.dYCCMNComboBox_3.currentIndex(),
                                     self.dYCCMNComboBox_4.currentIndex(), self.dYCCMNComboBox_5.currentIndex(),
                                     self.dYCCMNComboBox_6.currentIndex()))
        a = danhgia.replace("[", "", 2)
        b = a.replace(".", "", 2)
        c = b.replace("]", "", 2)
        if c == "0":
            c = "Kem"
        if c == "1":
            c = "Trung Binh"
        if c == "2":
            c = "Kha"
        if c == "3":
            c = "Gioi"
        return c


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_DialogXemNL()
    ui.setup(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
