# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QLSV_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pyodbc
from PyQt5 import QtCore, QtGui, QtWidgets

import DBHelper
from DBHelper import *
from QLNL_Layout import *

class Ui_Dialog1(object):
    def setup(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1300, 655)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 400, 1300, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)

        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(740, 100, 341, 141))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.ngYSinhLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.ngYSinhLabel_2.setObjectName("ngYSinhLabel_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ngYSinhLabel_2)
        self.dYCCMNComboBox_5 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.dYCCMNComboBox_5.setObjectName("dYCCMNComboBox_5")
        self.dYCCMNComboBox_5.addItem("")
        self.dYCCMNComboBox_5.addItem("")
        self.dYCCMNComboBox_5.addItem("")
        self.dYCCMNComboBox_5.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dYCCMNComboBox_5)
        self.aChLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.aChLabel_2.setObjectName("aChLabel_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.aChLabel_2)
        self.dYCCMNComboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.dYCCMNComboBox_3.setObjectName("dYCCMNComboBox_3")
        self.dYCCMNComboBox_3.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dYCCMNComboBox_3)
        self.chuyNMNLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.chuyNMNLabel_2.setObjectName("chuyNMNLabel_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.chuyNMNLabel_2)
        self.dYCCMNComboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.dYCCMNComboBox_4.setObjectName("dYCCMNComboBox_4")
        self.dYCCMNComboBox_4.addItem("")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dYCCMNComboBox_4)
        self.angLMViCLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.angLMViCLabel_2.setObjectName("angLMViCLabel_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.angLMViCLabel_2)
        self.angLMViCCheckBox_2 = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.angLMViCCheckBox_2.setObjectName("angLMViCCheckBox_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.angLMViCCheckBox_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_3.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_6)
        self.nhGiLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nhGiLabel.setObjectName("nhGiLabel")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.nhGiLabel)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(400, 100, 321, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.mGVLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.mGVLabel.setObjectName("mGVLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mGVLabel)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.HTLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.HTLabel.setObjectName("HTLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.HTLabel)
        self.HTLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.HTLineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.HTLineEdit.setObjectName("HTLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.HTLineEdit)
        self.namLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.namLabel.setObjectName("namLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.namLabel)
        self.namCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.namCheckBox.setObjectName("namCheckBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.namCheckBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_3)
        self.ngYSinhLabel_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.ngYSinhLabel_3.setObjectName("ngYSinhLabel_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ngYSinhLabel_3)
        self.ngYSinhDateEdit_3 = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.ngYSinhDateEdit_3.setObjectName("ngYSinhDateEdit_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ngYSinhDateEdit_3)
        self.aChLabel_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.aChLabel_3.setObjectName("aChLabel_3")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.aChLabel_3)
        self.aChLineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.aChLineEdit_3.setObjectName("aChLineEdit_3")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.aChLineEdit_3)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(240, 360, 681, 30))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(510, 50, 351, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 99, 271, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.nhGiLabel_2 = QtWidgets.QLabel(Dialog)
        self.nhGiLabel_2.setGeometry(QtCore.QRect(740, 250, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.nhGiLabel_2.setFont(font)
        self.nhGiLabel_2.setObjectName("nhGiLabel_2")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(840, 240, 61, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Tải dữ liệu cho Table, cho chọn dòng, bắt trỏ chuột.
        self.loaddataTable()
        self.tableWidget.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.tableWidget.clicked.connect(self.tableClick)

        # Tải dữ liệu cho Combobox Lớp
        self.comboboxLop()
        # Tải dữ liệu cho Combobox CN
        self.comboboxCN()

        self.label.setText(self.taoMaSV())
        # Nút chức năng
        self.pushButton_8.clicked.connect(self.nutLamMoi)
        self.pushButton_9.clicked.connect(self.nutThem)
        self.pushButton_10.clicked.connect(self.nutXoa)
        self.pushButton_11.clicked.connect(self.nutSua)
        self.pushButton_10.setEnabled(False)
        self.pushButton_11.setEnabled(False)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.clicked.connect(self.nutXemNL)
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "QLDSV"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Mã SV"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Họ Tên"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Phái"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Ngày Sinh"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Địa Chỉ"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Khóa Học"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Trạng Thái"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "CN"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Lớp"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "Đánh giá"))

        self.ngYSinhLabel_2.setText(_translate("Dialog", "Khóa Học:"))
        self.dYCCMNComboBox_5.setItemText(0, _translate("Dialog", "2017-2021"))
        self.dYCCMNComboBox_5.setItemText(1, _translate("Dialog", "2018-2022"))
        self.dYCCMNComboBox_5.setItemText(2, _translate("Dialog", "2019-2023"))
        self.dYCCMNComboBox_5.setItemText(3, _translate("Dialog", "2020-2024"))
        self.aChLabel_2.setText(_translate("Dialog", "Lớp Học:"))
        self.dYCCMNComboBox_3.setItemText(0, _translate("Dialog", "D19CQCN01"))
        self.chuyNMNLabel_2.setText(_translate("Dialog", "Chuyên Ngành:"))
        self.dYCCMNComboBox_4.setItemText(0, _translate("Dialog", "Công Nghệ Phần Mềm"))
        self.angLMViCLabel_2.setText(_translate("Dialog", "Đang Theo Học:"))

        self.nhGiLabel.setText(_translate("Dialog", "Đánh giá:"))
        self.label_3.setText(_translate("Dialog", "Tốt"))
        #cái này m gọi 1 hàm, hàm này select hết đống năng lực theo mã sv ra á.
        #đống này phải chuyển hết về số xong đưa vô cái val_x kia kìa


        self.mGVLabel.setText(_translate("Dialog", "Mã SV:"))
        self.label.setText(_translate("Dialog", "SV1"))
        self.HTLabel.setText(_translate("Dialog", "Họ Tên:"))
        self.namLabel.setText(_translate("Dialog", "Nam:"))
        self.ngYSinhLabel_3.setText(_translate("Dialog", "Ngày Sinh:"))
        self.aChLabel_3.setText(_translate("Dialog", "Địa Chỉ:"))
        self.pushButton_8.setText(_translate("Dialog", "Làm mới"))
        self.pushButton_9.setText(_translate("Dialog", "Thêm"))
        self.pushButton_10.setText(_translate("Dialog", "Xóa"))
        self.pushButton_11.setText(_translate("Dialog", "Sửa"))
        self.label_4.setText(_translate("Dialog", "QUẢN LÝ SINH VIÊN"))
        self.label_2.setText(_translate("Dialog", "                             Avatar"))
        self.pushButton.setText(_translate("Dialog", "Chọn Ảnh"))
        self.nhGiLabel_2.setText(_translate("Dialog", "Năng lực:"))
        self.pushButton_2.setText(_translate("Dialog", "Xem"))


    # Hàm tải dữ liệu lên cho table
    def loaddataTable(self):
        sqlquery="select * from sinhvien order by cast(substring(MaSV,3,10) as int)"
        self.tableWidget.setRowCount(50)
        tablerow=0
        # đặt số cột, và dữ liệu ở mỗi cột
        for row in ketnoi().execute(sqlquery):
            self.tableWidget.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[0]))
            self.tableWidget.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(str(row[1])))
            self.tableWidget.setItem(tablerow, 2, QtWidgets.QTableWidgetItem("Nam" if str(row[2]).__eq__("True") else "Nữ"))
            self.tableWidget.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(row[3]))
            self.tableWidget.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(str(row[4])))
            self.tableWidget.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(row[5]))
            self.tableWidget.setItem(tablerow, 6, QtWidgets.QTableWidgetItem("Đã nghỉ" if str(row[6]).__eq__("True") else "Đang theo học"))
            self.tableWidget.setItem(tablerow, 7, QtWidgets.QTableWidgetItem(self.searchTenCN(str(row[7]))))
            self.tableWidget.setItem(tablerow, 8, QtWidgets.QTableWidgetItem(self.searchTenLop(str(row[8]))))
            a=str(row[10])
            if a=="None":
                self.tableWidget.setItem(tablerow, 9, QtWidgets.QTableWidgetItem("Chưa có"))
            else:
                self.tableWidget.setItem(tablerow, 9, QtWidgets.QTableWidgetItem(a))

            tablerow+=1
        self.tableWidget.setRowCount(tablerow)
        # Khong cho edit
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)

        #Sửa kích cỡ cột
        self.tableWidget.setColumnWidth(0, 75)
        self.tableWidget.setColumnWidth(1, 200)
        self.tableWidget.setColumnWidth(2, 50)
        self.tableWidget.setColumnWidth(3, 100)
        self.tableWidget.setColumnWidth(5, 100)
        self.tableWidget.setColumnWidth(7, 200)

    # Hàm chuyển mã lớp sang tên lớp
    def searchTenLop(self, a):
        sqlquery = "SELECT tenlop FROM lop WHERE malop=N'" + a + "'"
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(","",2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
        return e.upper()
    # Hàm chuyển tên lớp sang mã lớp
    def searchMaLop(self, a):
        sqlquery = "SELECT malop FROM lop WHERE tenlop=N'" + a + "'"
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(", "", 2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
        return e

    # Hàm chuyển mãCN sang tênCN
    def searchTenCN(self, a):
        sqlquery = "SELECT tenCN FROM chuyennganh WHERE maCN='" + a + "'"
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(", "", 2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
        return e
    # Hàm chuyển tênCN sang mãCN
    def searchMaCN(self, a):
        sqlquery = "SELECT maCN FROM chuyennganh WHERE tenCN=N'" + a + "'"
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(", "", 2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
        return e

    # Hàm Tạo Combobox Lớp
    def comboboxLop(self):
        self.dYCCMNComboBox_3.clear()
        sqlquery = "SELECT tenlop FROM lop"
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(","",2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
            self.dYCCMNComboBox_3.addItem(e.upper())

    # Hàm Tạo Combobox CN
    def comboboxCN(self):
        self.dYCCMNComboBox_4.clear()
        sqlquery = "SELECT tenCN FROM chuyennganh"
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(", "", 2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
            self.dYCCMNComboBox_4.addItem(e)

    # Hàm bắt event table click tải dữ liệu lên ô để sửa
    def tableClick(self):
        self.pushButton_9.setEnabled(False)
        self.pushButton_10.setEnabled(True)
        self.pushButton_11.setEnabled(True)
        self.pushButton_2.setEnabled(True)

        row = self.tableWidget.currentRow()
        self.label.setText(self.tableWidget.item(row, 0).text())
        self.HTLineEdit.setText(self.tableWidget.item(row, 1).text())
        if self.tableWidget.item(row, 2).text() == "Nam":
            self.namCheckBox.setChecked(True)
        else:
            self.namCheckBox.setChecked(False)
        self.ngYSinhDateEdit_3.setDate(QtCore.QDate(int((str(self.tableWidget.item(row, 3).text())[0:4])),
                                                    int((str(self.tableWidget.item(row, 3).text())[5:7])),
                                                    int((str(self.tableWidget.item(row, 3).text())[8:10]))))
        self.aChLineEdit_3.setText(self.tableWidget.item(row, 4).text())
        if self.tableWidget.item(row, 5).text() == "2017-2021":
            self.dYCCMNComboBox_5.setCurrentIndex(0)
        if self.tableWidget.item(row, 5).text() == "2018-2022":
            self.dYCCMNComboBox_5.setCurrentIndex(1)
        if self.tableWidget.item(row, 5).text() == "2019-2023":
            self.dYCCMNComboBox_5.setCurrentIndex(2)
        if self.tableWidget.item(row, 5).text() == "2020-2024":
            self.dYCCMNComboBox_5.setCurrentIndex(3)

        if self.tableWidget.item(row, 6).text() == "Đang theo học":
            self.angLMViCCheckBox_2.setChecked(True)
        else:
            self.angLMViCCheckBox_2.setChecked(False)
        self.dYCCMNComboBox_4.setCurrentText(self.tableWidget.item(row, 7).text())
        self.dYCCMNComboBox_3.setCurrentText(self.tableWidget.item(row, 8).text())
        # self.label_3.setText(self.tableWidget.item(row, 11).text())
        self.label_3.setText(self.tableWidget.item(row, 9).text())

    def taoMaSV(self):
        sqlquery = "select maSV from sinhvien"
        max = 0
        for row in ketnoi().execute(sqlquery):
            b = str(row).replace("(", "", 2)
            c = str(b).replace("'", "", 2)
            d = str(c).replace(",", "", 2)
            e = str(d).replace(")", "", 2)
            ma = int((str(e)[2:4]))
            if ma > max:
                max = ma
        return "SV" + str(max + 1)

    # Nút Làm Mới
    def nutLamMoi(self):
        self.loaddataTable()
        self.tableWidget.clearSelection()
        self.label.setText(self.taoMaSV())
        self.HTLineEdit.setText("")
        self.namCheckBox.setChecked(False)
        self.ngYSinhDateEdit_3.setDate(QtCore.QDate.currentDate())
        self.aChLineEdit_3.setText("")
        self.dYCCMNComboBox_5.setCurrentIndex(0)
        self.dYCCMNComboBox_3.setCurrentIndex(0)
        self.dYCCMNComboBox_4.setCurrentIndex(0)
        self.angLMViCCheckBox_2.setChecked(False)
        self.pushButton_11.setEnabled(False)
        self.pushButton_9.setEnabled(True)
        self.pushButton_10.setEnabled(False)
        self.pushButton_11.setEnabled(False)
        self.pushButton_2.setEnabled(False)

    # Nút Thêm
    def nutThem(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()

        a=self.label.text()
        b=self.HTLineEdit.text()
        c="0"
        if self.namCheckBox.isChecked():
            c="1"
        d = str(str(self.ngYSinhDateEdit_3.date().year()) + "-" + str(self.ngYSinhDateEdit_3.date().month()) + "-" + \
                str(self.ngYSinhDateEdit_3.date().day()))
        e = self.aChLineEdit_3.text()
        f = self.dYCCMNComboBox_5.currentText()
        g = "1"
        if self.angLMViCCheckBox_2.isChecked():
            g = "0"
        h = self.searchMaCN(self.dYCCMNComboBox_4.currentText())
        i = self.searchMaLop(self.dYCCMNComboBox_3.currentText())
        j=""
        k=""

        query="insert into sinhvien values('"+a+"',N'"+b+"','"+c+"','"+d+"','"+e+"','"+f+"','"+g+"','"+h+"','"+i+"','"+j+"','"+k+"')"
        print(query)
        try:
            cur.execute(query)
            conn.commit()
            self.label.setText(self.taoMaSV())
            print("Ok")
            DBHelper.textThongBao = "         Thêm thành công."
            hienTB(self)
        except:
            print("Fail")
        self.nutLamMoi()

    # Nút Xóa
    def nutXoa(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()
        a = self.label.text()
        print(a)
        query = "delete from sinhvien where masv='" + a + "'"
        try:
            cur.execute(query)
            conn.commit()
            print("Ok")
            DBHelper.textThongBao = "         Xóa thành công."
            hienTB(self)
        except:
            print("Fail")
        self.nutLamMoi()

    # Nút Sửa
    def nutSua(self):
        conn = pyodbc.connect('Driver={SQL Server};'
                              'Server=DESKTOP-BDENHI9;'
                              'Database=quanlydiem1_HTTM;'
                              'Trusted_connection=yes;')
        cur = conn.cursor()

        a=self.label.text()
        b=self.HTLineEdit.text()
        c="0"
        if self.namCheckBox.isChecked():
            c="1"
        d = str(str(self.ngYSinhDateEdit_3.date().year()) + "-" + str(self.ngYSinhDateEdit_3.date().month()) + "-" + \
                str(self.ngYSinhDateEdit_3.date().day()))
        e = self.aChLineEdit_3.text()
        f = self.dYCCMNComboBox_5.currentText()
        g = "1"
        if self.angLMViCCheckBox_2.isChecked():
            g = "0"
        h = self.searchMaCN(self.dYCCMNComboBox_4.currentText())
        i = self.searchMaLop(self.dYCCMNComboBox_3.currentText())
        j=""
        k=""

        query = "update sinhvien set [HoTen]=N'" + b + "',[Phai]='" + c + "',[NgaySinh]='" + d + "',[DiaChi]='" + e + "',[KhoaHoc]='" + f + "',[TrangThaiNghi]='" + g + "',[MaCN]='" + h + "',[MaLop]='" + i + "',[HinhAnh]='" + j + "',[MaNL]='" + k + "'  where masv = '" + a + "'"
        print(query)
        try:
            cur.execute(query)
            conn.commit()
            print("Ok")
            DBHelper.textThongBao = "         Sửa thành công."
            hienTB(self)
        except:
            print("Fail")
        self.nutLamMoi()


    def nutXemNL(self):
        DBHelper.masv_formnl=self.label.text()
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_DialogXemNL()
        self.ui.setup(self.window)
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog1()
    ui.setup(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
